### General compositor behavior ###

general {
    gaps_in = 5
    gaps_out = 7
    border_size = 0
    col.inactive_border = rgba(ffffffff)
    layout = dwindle
    allow_tearing = false            #make true when blur is on
    resize_on_border = true
}

decoration {
    rounding = 14
    rounding_power = 4.0
    active_opacity = 1.0
    inactive_opacity = 1.0

  blur {
        enabled = no
        size = 8
        passes = 3
        noise = 0.02
        new_optimizations = on
        ignore_opacity = on
        xray = false
     }
  shadow {
        enabled = false
        ignore_window = true
        offset = 0 0
        range = 30
        render_power = 3
        color = rgba(00000044)
    }
}

animations {
    enabled = false
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windows, 1, 6, wind, slide
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsOut, 1, 5, winOut, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = border, 1, 1, liner
    animation = borderangle, 1, 30, liner, loop
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

dwindle {

    pseudotile = true
    smart_resizing = true
    preserve_split = true
    force_split = 0
}

master {
    new_status = master
}

misc {
    disable_hyprland_logo = true
    focus_on_activate = false
    force_default_wallpaper = 0
    vrr = 1
    vfr = true
}

xwayland {
    force_zero_scaling = true
}

