context.properties = {
    default.clock.rate = 48000
    default.clock.allowed-rates = [ 44100, 48000, 88200, 96000, 176400, 192000 ]
    default.clock.quantum = 256
    default.clock.min-quantum = 64
    default.clock.max-quantum = 512
    resample.quality = 10
}
